spring:
  profiles:
    include:
      - jwt
    active: local
  lifecycle:
    timeout-per-shutdown-phase: 20s

server:
  servlet:
    session:
      tracking-modes: cookie


logging.level:
  org.hibernate.SQL: debug

---

#Mysql 디비 설정
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # MySQL 설정
    url: jdbc:mysql://localhost:3306/testdb
    username: root
    password: 1111
  jpa:
    show-sql: true # true 설정시 JPA 쿼리문 확인 가능
    hibernate:
      ddl-auto: create-drop # DDL(create, alter, drop) 정의시 DB의 고유 기능을 사용할 수 있다.
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    defer-datasource-initialization: true
    open-in-view: false

  sql:
    init:
      mode: always

  data:
    redis:
      port: 6379
      host: 'localhost'

#  redis:
#    pool:
#      min-idle: 0
#      max-idle: 8
#      max-active: 8
#        host: 'localhost'

