POST http://localhost:8080/api/v1/spots/priority
Content-Type: application/json
accessToken: "Bearer "

{
  "direction": "북부",
  "viewWeight": 1,
  "priceWeight": 1,
  "facilityWeight": 2,
  "surroundWeight": 3,
  "isSameWeight" : true
}
