spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

  data:
    redis:
      port: 6379
      host: 'localhost'

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace